name: Set Variable

on: [push]

jobs:
  set-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        env:
          MY_VARIABLE: my-value
        run: echo "Variable value is $MY_VARIABLE"