name: Set Variable

on: [push]

env:
   REGISTRY: ghcr.io
   DOCKER_IMAGE_NAME: ${{ github.repository }}
   VAVA: place_holder


jobs:
  set-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo ">>>> $(echo $DOCKER_IMAGE_NAME | tr '[:upper:]' '[:lower:]') "


      - name: Set Variable 
        run: echo "VAVA=$(echo $DOCKER_IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Variable echo
        run: echo $VAVA

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Variable echo
        run: echo $VAVA
