name: Set Variable

on: [push]

env:
   REGISTRY: ghcr.io
   DOCKER_IMAGE_NAME: ${{ github.repository }}
   VAVA: pepe


jobs:
  set-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo ">>>> $(echo $DOCKER_IMAGE_NAME | tr '[:upper:]' '[:lower:]') "

      - name: Variable echo
        run: echo $VAVA

      - name: Reset Variable 
        run: cho "VAVA=nenem" >> $GITHUB_ENV

      - name: Variable echo
        run: echo $VAVA

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
